version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

parameters:
  browser:
    type: string
    default: "chrome" # Default browser
  feature_tag:
    type: string
    default: "@smoke" # Default test case tag
  environment:
    type: string
    default: "dev" # Default environment
  email:
    type: string
    default: "niroshan.desilva@carehires.com" # Default email

jobs:
  build:
    executor: java-executor
    parameters:
      browser:
        type: string
      feature_tag:
        type: string
      environment:
        type: string
      email:
        type: string
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb unzip binutils jq  # Added jq
            sudo apt-get update
            sudo apt-get install -y xvfb unzip binutils  # Added binutils
            sudo apt-get update
            sudo apt-get install -y xvfb
            sudo apt-get install -y unzip
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
            sudo unzip chromedriver.zip -d /usr/local/bin/
            rm chromedriver.zip

      - run:
          name: Run Tests
          command: |
            mvn clean test -Denv=<< parameters.environment >> -Dbrowser=<< parameters.browser >> -Dcucumber.filter.tags="<< parameters.feature_tag >>" \
              -Demail=<< parameters.email >>

      - run:
          name: Generate Cucumber Report
          command: |
            mvn compile exec:java -Dexec.mainClass="com.carehires.reports.CucumberReportGenerator"

      - store_artifacts:
          path: target/cucumber-reports  # Path to cucumber reports
          destination: cucumber-reports

      - store_artifacts:
          path: target/surefire-reports/test-report.zip
          destination: test-report.zip

workflows:
  version: 2
  test-workflow:
    jobs:
      - build:
          browser: << pipeline.parameters.browser >>
          feature_tag: << pipeline.parameters.feature_tag >>
          environment: << pipeline.parameters.environment >>
          email: << pipeline.parameters.email >>