version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

parameters:
  browser:
    type: string
    default: "chrome"
  feature_tag:
    type: string
    default: "@smoke"
  environment:
    type: string
    default: "dev"

jobs:
  test:
    executor: java-executor
    parameters:
      browser:
        type: string
        default: "<< parameters.browser >>"
      feature_tag:
        type: string
        default: "<< parameters.feature_tag >>"
      environment:
        type: string
        default: "<< parameters.environment >>"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb
            sudo apt-get install -y firefox
            sudo apt-get install -y unzip
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
            unzip chromedriver.zip -d /usr/local/bin/
            rm chromedriver.zip
            curl -sS -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
            tar -xzf geckodriver.tar.gz -C /usr/local/bin/
            rm geckodriver.tar.gz
      - run:
          name: Run Tests
          command: |
            mvn clean test -Dbrowser=<< parameters.browser >> -Dcucumber.options="--tags << parameters.feature_tag >>" -Denvironment=<< parameters.environment >>

workflows:
  version: 2
  test:
    jobs:
      - test:
          browser: << pipeline.parameters.browser >>
          feature_tag: << pipeline.parameters.feature_tag >>
          environment: << pipeline.parameters.environment >>