version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project

jobs:
  # Job for building only
  build-only-job:
    executor: maven-executor
    steps:
      - checkout

#      - restore_cache:
#          keys:
#            - maven-{{ checksum "pom.xml" }}
#            - maven-

#      - run:
#          name: Install dependencies
#          command: mvn dependency:resolve

#      - save_cache:
#          paths:
#            - ~/.m2
#          key: maven-{{ checksum "pom.xml" }}

  # Job for manual test execution
#  manual-test-job:
#    executor: maven-executor
#    parameters:
#      cucumber_tag:
#        type: string
#        default: "@smoke"  # Default Cucumber tag to run specific tests
#      environment:
#        type: string
#        default: "dev"     # Default environment, e.g., dev, staging, prod
#    steps:
#      - checkout

      # Install Google Chrome
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      # Cache Maven dependencies
#      - restore_cache:
#          keys:
#            - maven-{{ checksum "pom.xml" }}
#            - maven-

#     Install dependencies
      - run:
          name: Install dependencies
          command: mvn dependency:resolve

#      Build the project
      - run:
          name: Build the project
          command: mvn clean install

  # Define a job for running tests, only executed if triggered manually with `run_tests: true`
  manual-test-job:
    executor: maven-executor
    parameters:
      cucumber_tag:
        type: string
        default: "@smoke"
      environment:
        type: string
        default: "dev"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn dependency:resolve
      - run:
          name: Run tests
          command: |
            mvn test -Dcucumber.options="--tags << parameters.cucumber_tag >>" -Denv=<< parameters.environment >>
      # Store test results
      - store_test_results:
          path: target/surefire-reports
      # Store build artifacts (like JARs)
      - store_artifacts:
          path: target/surefire-reports
          destination: build-artifacts

workflows:
  version: 2
  workflow:
    jobs:
      - build-only-job
      - manual-test-job:
          requires:
            - build-only-job
          filters:
            branches:
              ignore: "*"
          parameters:
            cucumber_tag: << pipeline.parameters.cucumber_tag >>
            environment: << pipeline.parameters.environment >>

# Define pipeline parameters to use in manual triggers
parameters:
  run_tests:
    type: boolean
    default: false
  cucumber_tag:
    type: string
    default: "@smoke"
  environment:
    type: string
    default: "dev"