version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project

  selenium-executor:
    docker:
      - image: circleci/openjdk:17.0
    working_directory: ~/repo
    environment:
      CHROME_DRIVER_VERSION: latest
      CHROME_VERSION: latest

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout

      # Install Google Chrome
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      # Cache Maven dependencies
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install dependencies
          command: mvn dependency:resolve

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Run the tests
      - run:
          name: Build and Test with Maven
          command: mvn clean install

      - run:
          name: Run Cucumber Tests with Specific Tags
          command: |
            mvn test -Dtest="com.carehires.runner"
        

      # Store test results
      - store_test_results:
          path: target/surefire-reports

      # Store build artifacts (like JARs)
      - store_artifacts:
          path: target
          destination: build-artifacts

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build-and-test
