package com.carehires.steps.worker;

import com.carehires.actions.workers.WorkerBasicInformationActions;
import io.cucumber.java.en.And;

public class WorkerBasicInformationSteps {

    WorkerBasicInformationActions basicInformationActions = new WorkerBasicInformationActions();

    @And("User enters valid worker - basic information")
    public void enterBasicInformation() {
        basicInformationActions.enterWorkerBasicInformationData();
    }

    @And("User creates a worker in draft stage")
    public void createWorkerInDraft() {
        basicInformationActions.createWorkerInDraftStage();
    }

    @And("User edit worker profile data")
    public void editWorkerProfileData() {
        basicInformationActions.updateWorkerBasicInfo();
    }

    @And("User collects workerId from Basic Information page")
    public void getAutoGeneratedWorkerId() {
        basicInformationActions.getGeneratedWorkerId();
    }

    @And("User creates a worker")
    public void userCreatesAWorker() {
        basicInformationActions.completeCreateWorkerProcess();
    }

    @And("User enters valid non-British worker basic information")
    public void enteringNonBritishWorkerBasicInfo() {
        basicInformationActions.enterNonBritishWorkerBasicInformation();
    }
}
