package com.carehires.steps.agency;

import com.carehires.actions.agency.CreateAgencyBasicInformationActions;
import io.cucumber.java.en.And;

public class CreateAgencyBasicInformationSteps {
    CreateAgencyBasicInformationActions agencyBasicInformationActions = new CreateAgencyBasicInformationActions();

    @And("^User enters valid agency - basic information$")
    public void enterBasicInfo() {
        agencyBasicInformationActions.enterBasicInfo();
    }

    @And("User creates an agency in draft stage")
    public void createAgencyInDraftStage() {
        agencyBasicInformationActions.createAgencyInDraftStage();
    }

    @And("User moves to Agency - Basic Information page again")
    public void moveToBasicInformationStage() {
        agencyBasicInformationActions.moveToBasicInfoStage();
    }

    @And("User collects agencyId from Basic Information page")
    public void getAutoGeneratedAgencyId() {
        agencyBasicInformationActions.getGeneratedAgencyId();
    }

    @And("User creates an agency")
    public void createAgency() {
        agencyBasicInformationActions.completeCreateAgencyProcess();
    }
}