package com.carehires.actions.providers;

import com.carehires.common.GlobalVariables;
import com.carehires.pages.providers.SearchProviderPage;
import com.carehires.utils.BasePage;
import com.carehires.utils.DataConfigurationReader;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.PageFactory;

import java.util.List;

public class SearchProviderActions {

    SearchProviderPage searchPage;

    private static final String ENTITY = "provider";
    private static final String EDIT_YML_FILE = "provider-edit";
    private static final String YML_HEADER = "Company Information";
    private static final String ADD = "Add";


    private static final Logger logger = LogManager.getFormatterLogger(ProviderSiteManagementActions.class);

    public SearchProviderActions() {
        searchPage = new SearchProviderPage();
        try {
            PageFactory.initElements(BasePage.getDriver(), searchPage);
        } catch (BasePage.WebDriverInitializationException e) {
            throw new RuntimeException(e);
        }
    }

    public void searchByText() {
        BasePage.waitUntilPageCompletelyLoaded();

        String id = GlobalVariables.getVariable("providerId", String.class);
        BasePage.waitUntilElementDisplayed(searchPage.searchByText, 30);

        // Wait until search results are available (e.g. providerIds list is populated)
        BasePage.waitUntilElementPresent(searchPage.firstProviderId, 30);

        int row = getProviderFromTheList(id);

        // Check if row is valid before trying to click
        if (row >= 0 && row < searchPage.providerIds.size()) {
            BasePage.clickWithJavaScript((searchPage.providerIds).get(row));
        } else {
            throw new IllegalStateException("Provider ID not found in the list.");
        }
    }

    private int getProviderFromTheList(String providerId) {
        List<WebElement> ids = searchPage.providerIds;

        // Check if the list is empty
        if (ids.isEmpty()) {
            throw new IllegalStateException("No providers found in the list.");
        }

        // Loop through the list to find the matching providerId
        for (int i = 0; i < ids.size(); i++) {
            if (BasePage.getText(ids.get(i)).equals(providerId)) {
                return i;
            }
        }

        // If no match found, return -1 to indicate it
        return -1;
    }

    public void searchByAutoGeneratedId() {
        logger.info("<<<<<<<<<<<<<<<<<<<<<<< Searching previously created provider >>>>>>>>>>>>>>>>>>>>");
        BasePage.waitUntilPageCompletelyLoaded();
        String companyName = DataConfigurationReader.readDataFromYmlFile(ENTITY, EDIT_YML_FILE, YML_HEADER, ADD, "CompanyName");
        BasePage.waitUntilElementPresent(searchPage.firstProviderId, 30);
        BasePage.clearAndEnterTexts(searchPage.searchByText, companyName);
        BasePage.clickOnEnterKey(searchPage.searchByText);

        // Wait until search results are available (e.g. providerIds list is populated)
        BasePage.waitUntilElementPresent(searchPage.firstProviderId, 30);
        BasePage.clickWithJavaScript(searchPage.firstProviderId);
    }
}