package com.carehires.actions.agency;

import com.carehires.actions.workers.SearchWorkerActions;
import com.carehires.common.GlobalVariables;
import com.carehires.pages.agency.SearchAgencyPage;
import com.carehires.utils.BasePage;
import com.carehires.utils.DataConfigurationReader;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.PageFactory;

import java.util.List;

public class SearchAgencyActions {

    private final SearchAgencyPage searchPage;
    private static final Logger logger = LogManager.getFormatterLogger(SearchWorkerActions.class);

    public SearchAgencyActions() {
        searchPage = new SearchAgencyPage();
        try {
            PageFactory.initElements(BasePage.getDriver(), searchPage);
        } catch (BasePage.WebDriverInitializationException e) {
            throw new RuntimeException(e);
        }
    }

    public void searchByText() {
        logger.info("<<<<<<<<<<<<<<<<<<<<<<< Searching the relevant agency by using the agency name >>>>>>>>>>>>>>>>>>>>");

        BasePage.waitUntilPageCompletelyLoaded();

        //wait until profile status get updated
        BasePage.waitUntilElementPresent(searchPage.searchByText, 30);
        String agencyName = DataConfigurationReader.readDataFromYmlFile("agency", "agency-create", "Basic Info", "Add", "BusinessName");
        BasePage.typeWithStringBuilder(searchPage.searchByText, agencyName);
        BasePage.clickOnEnterKey(searchPage.searchByText);
    }

    public void findAgencyByAutogeneratedAgencyId() {
        logger.info("<<<<<<<<<<<<<<<<<<<<<<< Searching the relevant agency by providing the auto generated agency id >>>>>>>>>>>>>>>>>>>>");

        BasePage.waitUntilPageCompletelyLoaded();
        String id = GlobalVariables.getVariable("agencyId", String.class);
        BasePage.waitUntilElementDisplayed(searchPage.searchByText, 30);
        // Wait until search results are available (e.g. agencyIds list is populated)
        BasePage.waitUntilElementPresent(searchPage.firstAgencyId, 30);
        int row = getAgencyFromTheList(id);

        // Check if row is valid before trying to click
        if (row >= 0 && row < searchPage.agencyIds.size()) {
            BasePage.clickWithJavaScript((searchPage.agencyIds).get(row));
        } else {
            throw new IllegalStateException("Agency ID not found in the list.");
        }
    }

    public void searchRecentlyUpdatedAgency() {
        BasePage.waitUntilPageCompletelyLoaded();
        String id = GlobalVariables.getVariable("agencyId", String.class);
        BasePage.waitUntilElementDisplayed(searchPage.searchByText, 30);

        // Wait until search results are available (e.g. agency id list is populated)
        BasePage.waitUntilElementPresent(searchPage.firstAgencyId, 30);
        int row = getAgencyFromTheList(id);

        // Check if row is valid before trying to click
        if (row >= 0 && row < searchPage.agencyIds.size()) {
            BasePage.clickWithJavaScript((searchPage.agencyIds).get(row));
        } else {
            throw new IllegalStateException("Agency ID not found in the list.");
        }
    }

    private int getAgencyFromTheList(String agencyId) {
        List<WebElement> ids = searchPage.agencyIds;

        // Check if the list is empty
        if (ids.isEmpty()) {
            throw new IllegalStateException("No agencies found in the list.");
        }

        // Loop through the list to find the matching agencyId
        for (int i = 0; i < ids.size(); i++) {
            if (BasePage.getText(ids.get(i)).equals(agencyId)) {
                return i;
            }
        }

        // If no match found, return -1 to indicate it
        return -1;
    }
}
